default:
        num_steps: !!float 2e6
        seq_len: 64
        cfc_params:
                clipnorm: 1
                optimizer: "Adam"
                batch_size: 128
                size: 64
                embed_dim: 192
                embed_dr: 0.0
                base_lr: 0.02
                decay_lr: 0.95
                backbone_activation: "silu"
                backbone_dr: 0.1
                backbone_units: 256
                backbone_layers: 1
                weight_decay: !!float 1e-06
                use_mixed: False
                no_gate: False
